# Generated by Django 3.1.2 on 2020-10-22 22:17

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cuerpo', ckeditor.fields.RichTextField()),
                ('autor_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Blog.autor')),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='comentario_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Blog.comentario'),
        ),
    ]
