# Generated by Django 3.1.2 on 2020-10-22 21:51

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=35)),
                ('cuerpo', ckeditor.fields.RichTextField()),
                ('autor_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Blog.autor')),
            ],
        ),
    ]
