# Generated by Django 3.1.2 on 2020-10-22 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20201022_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='autor_id',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='comentario_id',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='autor_id',
        ),
        migrations.DeleteModel(
            name='Autor',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
