# Generated by Django 3.1.3 on 2020-11-05 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='carrera',
            field=models.CharField(default='General', max_length=50),
        ),
    ]
